//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDschool.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int IdJ { get; set; }
        public int IdS { get; set; }
        public int IdCl { get; set; }
        public string Appraisal { get; set; }
        public int IdL { get; set; }
        public int IdT { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Lessons Lessons { get; set; }
        public virtual Studs Studs { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
